### ISSUE TITLE
implement structure: data-store(~/.gcctx) file format

### ISSUE THREAD

**Issue by ykamenashi** [ykamenashi/gcctx#9]
## TODO

- [ ] write this entry to README.MD
- [ ] datastore READ function
- [ ] datastore CLEANUP function
- [ ] datastore WRITE function

### structure
```
dir DIR-NAME1
* <shortname1> <longname1(fullpath)>
* <shortname2> <longname2(fullpath)>
* <shortname3> <longname3(fullpath)>
...
dir DIR-NAME2
* <shortname4> <longname4(fullpath)>
* <shortname5> <longname5(fullpath)>
...
```
* non-existent entry: automatically removed by gcctx itself.

### query plan
```
while read LINE
do
  if [ "$LINE" -eq "@@@@@@" ] ; then
    #### something
    if [[ "$LINE ~= "@@@@@@" ] ; then
      #### something
    fi
  fi
done < ~/.gcctx
```
